repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.1-1
    hooks:
    -   id: flake8
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/asottile/reorder_python_imports
    sha: v0.3.5
    hooks:
    -   id: reorder-python-imports
        language_version: python3.6
exclude: docs/
